=== Bost/h3270/webapp/WEB-INF/etc/h3270-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT colorschemes (scheme+)>
<!ATTLIST colorschemes default CDATA #REQUIRED>
<!ELEMENT configuration (fonts,colorschemes)>
<!ELEMENT exec-path (#PCDATA)>
<!ELEMENT font EMPTY>
<!ATTLIST font
	description CDATA #IMPLIED
	name NMTOKEN #REQUIRED
>
<!ELEMENT fonts (font+)>
<!ATTLIST fonts default NMTOKEN #REQUIRED>
<!ELEMENT h3270 (exec-path,template-dir,configuration)>
<!ELEMENT scheme EMPTY>
<!ATTLIST scheme
	name CDATA #REQUIRED
	phbg NMTOKEN #REQUIRED
	phfg NMTOKEN #REQUIRED
	pibg NMTOKEN #REQUIRED
	pifg NMTOKEN #REQUIRED
	pnbg NMTOKEN #REQUIRED
	pnfg NMTOKEN #REQUIRED
	uhbg CDATA #REQUIRED
	uhfg NMTOKEN #REQUIRED
	uibg CDATA #REQUIRED
	uifg NMTOKEN #REQUIRED
	unbg CDATA #REQUIRED
	unfg NMTOKEN #REQUIRED
>
<!ELEMENT template-dir (#PCDATA)>

=== Bost/h3270/webapp/WEB-INF/h3270-config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE h3270 SYSTEM "etc/h3270-config.dtd">
<h3270>
	<!-- <exec-path>/usr/local/bin</exec-path> -->
	<!-- <style>h3270</style> -->
	
	<configuration>
		<fonts default="times">
			<font name="courier" description="Courier" />
			<font name="freemono" description="Free Mono" />
			<font name="terminal" description="Terminal" />
			<font name="couriernew" description="Courier New" />
			<font name="monospace" description="Monospace" />
			<font name="times" description="Times" />
		</fonts>
		<colorschemes default="White Background">
			<scheme name="White Background" pnfg="black" pnbg="white" 
				pifg="blue" pibg="white" phfg="white" phbg="white" unfg="green" 
				unbg="lightgrey" uifg="red" uibg="lightgrey" uhfg="red" 
				uhbg="lightgrey" />
			<scheme name="Dark Background" pnfg="cyan" pnbg="black" 
				pifg="white" pibg="black" phfg="black" phbg="black" unfg="lime" 
				unbg="#282828" uifg="red" uibg="#282828" uhfg="red" 
				uhbg="#282828" />
			<scheme name="Amber" pnfg="orange" pnbg="black" pifg="white" 
				pibg="black" phfg="black" phbg="black" unfg="white" 
				unbg="#282828" uifg="red" uibg="#282828" uhfg="orange" 
				uhbg="#282828" />
			<scheme name="Black and White" pnfg="black" pnbg="white" 
				pifg="black" pibg="white" phfg="white" phbg="white" 
				unfg="black" unbg="lightgrey" uifg="black" uibg="lightgrey" 
				uhfg="black" uhbg="lightgrey" />
		</colorschemes>
	</configuration>
</h3270>
